### ISSUE TITLE
Can't enable line number while theme is installed

### ISSUE THREAD

**Issue by gozes** [soulshined/Visual-Studio-Code-Naysayer88-Color-Theme#1]
So I tried every way possible but seems that as long as I have this theme install, doesn't have to be enabled, you can't enable line nubes. Only way found to fix his issue was by uninstalling the theme.

**Comment by soulshined** [comment]
@gozes that is effectively how jon blow has his emacs editor setup. Although, it should be a personal choice I agree. You can enable them, but I goofed and set the lineNumber font color to the same as the background [ref](https://github.com/soulshined/Visual-Studio-Code-Naysayer88-Color-Theme/blob/7325c3dbf8e1b591021b5550906ecdb0fac1c142/themes/Naysayer88-color-theme.json#L78) 🤦‍♂️ I'm deeply sorry about any amount of time you spent trying to figure it out. However, thanks for sharing. 

For those interested, I'll have an update good to go by Friday
